<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Coating' => '',
    'Color' => '',
    'Color Type' => '',
    'Created At' => '',
    'Custom Number' => '',
    'Diameter' => '',
    'Diopter Lens Type' => '',
    'Diopter Type' => '',
    'Finished At' => '',
    'Function' => '',
    'L Add' => '',
    'L Axs' => '',
    'L Cyl' => '',
    'L Prism Diopter' => '',
    'L Prism Direction' => '',
    'L Sph' => '',
    'Lens Custom ID' => '定制编号',
    'Material' => '',
    'Order Rep' => '',
    'Ordered At' => '',
    'Quantity' => '',
    'R Add' => '',
    'R Axs' => '',
    'R Cyl' => '',
    'R Prism Diopter' => '',
    'R Prism Direction' => '',
    'R Sph' => '',
    'Ref Number' => '',
    'Refractive Index' => '',
    'Remark' => '',
    'Status' => '',
    'Supplier' => '',
    'Surface' => '',
];
