<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Commission Rate' => '提成比例',
    'Commission Rate (%)' => '提成比例（%）',
    'Country/Region of Destination' => '目的国/地区',
    'Create' => '新建',
    'Create Order' => '新建订单',
    'Date Format' => '日期格式',
    'Leave Empty Without ID' => '无编号可以不填',
    'No' => '否',
    'Order Information' => '订单信息',
    'Payment Method' => '付款方式',
    'Remark' => '备注',
    'Reset' => '重置',
    'Update' => '更新',
    'View Orders' => '查看订单',
    'Yes' => '是',
    'Client Name' => '客户姓名',
    'Country/Region' => '国家/地区',
    'Currency' => '货币',
    'Custom Declaration' => '是否报关',
    'Delete' => '删除',
    'Delete Orders' => '删除订单',
    'Incoterm' => '贸易术语',
    'Order Amount' => '订单金额',
    'Order Date' => '订单日期',
    'Order ID' => '订单编号',
    'Sales Representative' => '销售代表',
    'Shipping Charges' => '订单运费',
    'Status' => '状态',
];
