<?php
/**
 * Created by PhpStorm.
 * User: Paul
 * Date: 2017/9/2
 * Time: 10:23
 */

namespace common\modules\customer;


class Module extends \yii\base\Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}